### ISSUE TITLE
Package naming suggestions

### ISSUE THREAD

**Issue by pruett** [hashicorp/octavo#1]
Drop in your suggestions below in this thread....

- Vote up with 👍

**Comment by pruett** [comment]
`next-react-component-library`

**Comment by BrandonRomano** [comment]
`nextbook`

**Comment by jescalan** [comment]
`swingset` (via kyle)

**Comment by jescalan** [comment]
`next-playground`

**Comment by EnMod** [comment]
`vignette` 

It has a `0.1.0` release with no publishes for 5 years...worth asking the maintainer perhaps?

**Comment by jmfury** [comment]
```
turnery
```

> _the process or art of forming or shaping objects on a lathe.
objects or articles fashioned on a lathe collectively.
a workshop where such work is done._

**Comment by jonathantneal** [comment]
`octavo`

**Comment by jescalan** [comment]
And it is swingset!
