### ISSUE TITLE
defaultValue is not the default prop value

### ISSUE THREAD

**Issue by jonathantneal** [hashicorp/octavo#5]
When using a `props.json5` file, its `defaultValue` property is used to control the default control value in a `<KnobsComponent>`. This is confusing, as the `props.json5` file refers to "props" in its name, suggesting `defaultValue` would be the default value in the shape of the data, like [`defaultProps` in React](https://reactjs.org/docs/typechecking-with-proptypes.html#default-prop-values), or a [default parameter in JS](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters).

It might make more sense to move context-specific props into their own object.

```js
{
  inline: {
    description: 'Determines whether to display the alert inline and only with a tagline',
    type: 'boolean',
    knob: {
      type: 'checkbox',
      defaultValue: false
    }
  }
}
```

**Comment by jescalan** [comment]
Great call, resolved
